= Моделирование процесса приготовления стейка рибай
Tepex <tepex@mail.ru>
1.0, 28/I-2026
:source-highliter: rouge

Проект не закончен и в стадии разработки. В данном учебно-демонстрационном проекте моделируется условный производственный процесс
приготовления стейка рибай. Процесс состоит из элементарных последовательно-параллельных
операций. Цель данного проекта — демонстрация практического воплощения подходов `DDD`, 
`Railway Oriented Programming`, `Functional Programming`, `Functional Declarative Design`,
`Tagless Final` на языке Котлин.
// TODO: добавить ссылки на термины

== Введение
Данный проект призван продемонстрировать на практике воплощение идей, парадигм и концепций, которые
актуальны на данный момент в ИТ-отрасли и послужить основой для применения в своих собственных 
разработках. В основе проекта послужила статья [А. Гранина] о методологии функционального 
декларативного проектирования (FDD), где показан подход к декларативному представлению процесса в 
виде структуры и ее интерпретации — разделения на *ЧТО* надо сделать, и *КАК* надо сделать. В этом
проекте осуществлена эта методология с адаптацией на языке Котлин.

В качестве примера взят условный процесс приготовления стейка рибай, который состоит из цепочки
последовательно-параллельных операций. Сам этот процесс представлен в виде декларативного кода на
eDSL, созданным в рамках данного проекта. В проекте показано, как можно описать и протестировать
некий производственный процесс используя лишь абстракции, тем самым разделив разработку доменной
модели на концептуальную часть и конкретные реализации. Это обеспеспечивает разделение труда между
бизнес-аналитиками и разработчиками, которые, как будет показано ниже, легко заменяются за счет
кодогенерации. Это составляет более 4-х кратную экономию только лишь написания кода, не говоря уже
о посдедующей поддержке кодовой базы проекта при частых и срочных изменениях на концептуальном
уровне.

В приведенном в статье примере приводится упрощенный процесс приготовления сэндвича. В
данном проекте процесс для разнообразия и "живости" дополняется изменением состояния ресурса на
каждом этапе операций: изменение характеристик, учет затраченного времени и добавленной стоимости.

Дополнительно в рамках данного проекта понадобилось реализовать модель репозитория ресурсов. В этих
подпроектах реализованы классические подходы к организации конкурентного досткупа к разделяемому
ресурсу: оптимистическая блокировка и версионирование данных в зависимости от способа хранения
ресурса, а также реализация попыток экспоненциального доступа с джиттером.

// TODO: обоснование подробно для чего для аналитиков


== Принцип работы, вводная, описание процесса

== Структура проекта

== Принципы, подходы и стиль кодовой базы
link:CONSIDERATION.adoc[Соглашение о принципах и правилах кодовой базы].
https://github.com/tepex/kddd-ksp-dev/blob/dsl-builder/Profession-de-foi.adoc[Профессиональные принципы]

== Итог

== Ссылки



При моделировании и реализации различной производственной деятельности как ИТ-систем возникает 
необходимость в организации процессов и операций, как элементарных составных частей этих процессов в 
рамках какой-либо предметной области (домена). Это, например, такие известные системы, как Camunda, 
Gradle, системы CI/CD и пр. Но что, если вам понадобится организовать свою систему выполнения 
процессов в рамках своего домена? Такие системы должны отражать какие-либо реальные производственные
(бизнес) процессы продиктованныне требованиями заказчика, бизнеса, внешними факторами, и, 
следовательно, носят корневую составляющую вашего домена. Такой корневой (core) домен должен обладать
соответветствующей гибкостью для обеспечения быстроты и легкости внесения изменений, дабы обеспечить 
конкурентное преимущество и снизить стоимость владения системой. 



