= Модуль хранения данных
Tepex <tepex@mail.ru>
1.0, 12/I-2026
:source-highliter: rouge

Модуль реализует абстракцию слота хранения — контейнера для размещения ресурсов (продуктов).
В парадигме DDD — _Supporting subdomain_.

== Введение
Данный модуль представляет из себя некоторое подобие специализированной базы данных отражающей
хранение ресурсов в различном виде: поштучном, весовом или в собственной упаковке. Например,
такие виды ресурсов как соль, сахар, специи удобно хранить в некотором общем контейнере, откуда можно
извлекать необходимое весовое количество. Тоже касается и штучных ресурсов, когда нужно хранить в
едином контейнере определенное количество предметов с общим сроком годности, например, яйца или
пучки зелени. Также и жидкости, такие как масло, молоко, соусы и прочее. Некоторые ресурсы могут быть
представлены в собственной упаковке со своими характеристиками веса и сроком годности, например,
колбасная или сырная нарезка. В рамках общего проекта используется упакованное мясо для стейков.

Такое разграничение необходимо для обеспечения функционала слота: отпуск ресурса в необходимом
количестве (поштучно, на развес), принятие ресурса на хранение и контроля срока годности. Важная
особенность разделения слотов по жизненному циклу: слоты могут быть одноразовыми (Disposable) и
многоразовыми (Reusable). Одноразовые слоты прекращают свое существование после добавления нового
ресурса, тогда как многоразовые слоты могут принимать и отпускать ресурсы многократно. Например,
поштучный слот для яиц будет одноразовым, так как при добавлении новой партии яиц, старая
теряет актуальность. А вот добавление новой упаковки мяса в слот многоразового хранения не влияет на
уже находящиеся там упаковки и такой слот не пересоздается заново, а используется уже имеющееся
хранилище.

Разный ЖЦ слотов влечет за собой разные подходы к реализации доступа к общему ресурсу. В одноразовых
слотах можно использовать простую блокировку на время выполнения операции, тогда как в многоразовых
слотах необходимо реализовывать механизм оптимистической блокировки (optimistic locking) с
помощью версионирования. Это позволит избежать проблем с конкурентным доступом к данным слота.

== Функциональные требования
* Поддержка поштучного, весового и упакованного хранения ресурсов.
* Поддержка одноразовых и многоразовых слотов.
* Операции добавления и извлечения ресурсов c учетом количества ресурса.
* Потокобезопастный доступ.
* Контроль ЖЦ одноразовых слотов.
* Версионирование для обеспечения оптимистической блокировки в многоразовых слотах.
* Независимость формата хранения ресурсов.

Что каксаетя независимости формата хранения ресурсов, в целях упрощения реализации, полагается, что
ресурсы сериализуются в JSON-формат. Это позволяет не привязываться к конкретной структуре ресурса.
Также JSON-строка генерируется и парсится не с помощью стандартных библиотек, а вручную «на коленке».

== Тестирование
Для Unit-тестов используются библиотеки https://kotest.io[Kotest] и https://mockk.io[MockK]. Чтобы
протестировать конкурентный доступ к слоту и смоделировать реальные сценарии одновременного использования,
используется поддержка корутин из Kotest. Для этого в цикле запускаются многочисленные попытки добавления
и извлечения ресурсов из слота с помощью `launch` и `async`. В тестах проверяется корректность
итогового состояния слота после выполнения всех конкурентных операций. Для этого в слот необходимо
инжетировать специальный тестовый диспетчер `StandartTestDispatcher`, который позволяет контролировать
выполнение корутин в тестах.

